# Check out https://docs.codemagic.io/yaml/yaml/ for more information

workflows:
    flutter-widget:
        name: Flutter Widget
        environment:
            flutter: dev
        scripts:
            - flutter packages pub get
            - flutter test