name: simple_todos_bloc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.1.0 <2.0.0"        # เพิ่ม meta
  equatable: ^1.2.2             # เพิ่ม equatable
  flutter_bloc: ^5.0.1         # เพิ่ม flutter_bloc
  path_provider: ^1.6.11         # เพิ่ม path_provider สำหรับทำ local storage เป็น text file
  json_annotation: ^3.0.1       # เพิ่ม json_annotation ไว้แปลง ข้อมูลในรูปแบบ class ให้กลายเป็น json จะได้นำไปจัดเก็บเป็น text file ได้

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0          # เพิ่ม build_runner สำหรับ json_annotation
  json_serializable: ^3.0.1     # เพิ่ม json_serializable สำหรับ json_annotation


flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
